export const recipes_data: Recipe[] = [
  {
    id: 'a542e833-edfe-44a3-a6f1-7358b115af4b',
    title: 'Frankfurter salad with mustard dressing',
    difficulty: 'easy',
    ingredients: [
      '675 g (1.5 lb) small new salad potatoes such as Pink Fir Apple',
      '3 eggs (not too fresh for hard-boiled eggs)',
      '350 g (12 oz) frankfurters - Siamese cats love Frankfurters!',
      '1 lettuce',
      ' chopped.  Any type will do',
      ' a Chinese cabbage worked well the last time I made this.',
      '1 packet of young spinach leaves or rocket leaves',
      ' about 225 g (8 oz)',
      'A handful of chives',
      ' chopped (if in season)',
      'Dressing',
      '3 tablespoons (30 ml) olive oil',
      '1 tablespoon (15 ml) white wine vinegar',
      'Pinch of sugar',
      'Pinch of salt',
      'Dash of lemon juice',
      '2 teaspoons (10 ml) American squeezy mustard',
      '1 teaspoon (5 ml) caraway seeds',
      ' crushed in a pestle and mortar',
    ],
    preparationTime: 15,
    totalTime: 25,
    instructions:
      'Bring the potatoes to boil and simmer for 15 minutes in lightly salted water,Drain, cover and keep warm,Hard-boil the eggs for 12 minutes, refresh in cold water, peel and cut into quarters,With a very sharp knife, make a corkscrew shaped score around frankfurters from one end to the other,Bring to the boil and simmer for 5 minutes, drain and keep warm,Add the dressing ingredients to a bowl and whisk well until combined.  Alternatively use a salad shaker or a screw-topped jar,Mix half of the dressing with the spinach and lettuce leaves and the other half with the potatoes and the frankfurters,Divide the salad amongst 4 large plates and dress with the hard-boiled eggs,Season to taste and serve immediately',
    photo: 'https://live-contentacms.pantheonsite.io/sites/default/files/5631421314_9db3bd149d_b.jpg',
    category: 'Salad',
  },
  {
    id: '84cfaa18-faca-471f-bfa5-fbb8c199d039',
    title: 'Majorcan vegetable bake',
    difficulty: 'easy',
    ingredients: [
      '400g can peeled plum tomatoes',
      ' chopped',
      '1 tablespoon fresh oregano or marjoram',
      ' chopped',
      '3 tablespoon olive oil plus a little more to dress the dish with',
      '6 fat Cloves of garlic (or to taste)',
      ' half peeled and crushed',
      ' the remaining half peeled and roughly chopped',
      '1 aubergine',
      ' sliced',
      '1 sweet bell pepper of any colour',
      '1 large onion',
      ' peeled and sliced',
      '650g potatoes',
      ' peeled and sliced: Desiree',
      ' King Edward',
      ' Lady Balfour',
      ' Maris Piper',
      ' Melody etc.',
      'sea salt and freshly ground black pepper',
    ],
    preparationTime: 15,
    totalTime: 25,
    instructions:
      'Add 1.5  tablespoons of the oil to a pan and sizzle the garlic for a minute and then add the tomatoes, oregano, season and simmer for 10 minutes to reduce a little.,Toss the aubergine, pepper and onion in the remaining oil, season and arrange in a baking tray and oven roast for 10 minutes.,Remove from the oven and arrange the potatoes and vegetables in layers.,Pour over the tomato sauce, add a grind of black pepper and a glug of olive oil.,Cover with tin foil and bake for 1 hour, removing the tin-foil half way through.',
    photo: 'https://live-contentacms.pantheonsite.io/sites/default/files/img_9212-683x1024.jpg',
    category: 'Main course',
  },
  {
    id: 'b0fc9671-0dca-474c-ad55-ab793d8866ca',
    title: 'Silverside of beef in a pressure cooker',
    difficulty: 'middle',
    ingredients: [
      '2 kg (4 lb) joint of beef silverside',
      '2 tablespoons oil',
      'Freshly ground black pepper',
      '4 medium carrots',
      ' peeled and sliced',
      '3 sticks of celery',
      ' coarsely chopped',
      '10 dried shiitake mushrooms',
      '500ml hot beef stock',
      '1 bottle of robust red wine',
      '6 large cloves of garlic',
      ' peeled',
      '1 large onion',
      ' sliced',
      '2 tablespoons tomato puree',
      'A squeeze of lemon juice',
      '3 tablespoons Worcestershire sauce',
      '1 Bouquet garni - made up from what was in the garden at the time: sage',
      ' rosemary',
      ' parsley',
      ' cutting celery',
      ' bay leaves.',
    ],
    preparationTime: 35,
    totalTime: 45,
    instructions:
      'Pat the joint dry and cover with a good grind of black pepper,Leaving the netting on the joint, heat the oil in a frying pan and sear the meat for about 3 minutes on each side.,Chop the dried mushrooms into quarters,Add the carrots, onions, garlic, mushrooms to the pressure cooker and sit the seared meat on top, jiggle it around a little if you need more room.,Deglaze the meat pan with a little red wine and add that to the mix.,Pour over the remaining red wine, beef stock, Worcestershire sauce and tomato purée and mix well.,Fit the lid, bring up to pressure and cook on high pressure for 3 hours.,Depressurise naturally,Remove the silverside from the pressure cooker and allow to rest, under tented foil for 15 minutes.,Using a slotted spoon, ladle just more than half of the vegetables and a little stock into a food processor and blend to make a gravy.,Add the gravy back to the pan with the remaining vegetables, add a few tablespoons of yellow cornmeal if it needs thickening.  Bring back to the boil, uncovered, for a short while to thicken when ready to serve.,Slice the silverside, reheat the gravy and serve.',
    photo: 'https://live-contentacms.pantheonsite.io/sites/default/files/1098144-pxhere.jpg',
    category: 'Main course',
  },
  {
    id: '5714ae54-7cf3-43bc-a5f9-1416233a85b6',
    title: 'Blue cheese and walnut pizza',
    difficulty: null,
    ingredients: [
        "Olive oil",
        "1 portion of pizza dough - makes 2 pizzas",
        "150 g Saint Agur Blue cheese",
        " crumbled",
        "6 tablespoons of crushed walnuts"
    ],
    preparationTime: 0,
    totalTime: 14,
    instructions:
    "Make 1 pizza per person.,Dust your work surface with fine yellow cornmeal.,Divide the pizza dough into two and roll out into two thin 25.5 cm (10 inch) pizzas.,Prick the pizza all over with a fork. This prevents it puffing up too much and burning while it is cooking.,Place the pizza dough on a pizza peel that has been dusted with fine yellow cornmeal.,Preheat the pizza stone under a very hot grill.,With a deft move, slide the pizza dough from the pizza peel, on to the preheated pizza stone.,Cook for about 2 minutes on one side only, until lightly browned.,Remove from the oven.,Drizzle the top of the pizza with a little olive oil.,Arrange the walnuts over the pizza and top with the crumbled blue cheese.,Bake the pizza until the cheese starts to melt and bubble-this only takes a few minutes under a very hot grill.,Keep the fist pizza warm at the bottom of the oven whilst you make the second.",
    photo: 'https://live-contentacms.pantheonsite.io/sites/default/files/716259-pxhere.jpg',
    category: 'Snack'
  },
];
